apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scaling-demo
  namespace: argocd
spec:
  project: default
  source:
    # Git repo URI
    repoURL: https://github.com/hhoang219/microservices-demo.git
    # Select branch to deploy
    targetRevision: scaling-demo
    # Path to kubernete yaml folder
    path: release
    # Apply kubernetes yaml files in child folders
    directory:
      recurse: true
  destination:
    # Which cluster to deploy. kubernetes.default.svc is the cluster where ArgoCD is deployed
    server: https://kubernetes.default.svc
    # Namespace for your application
    namespace: scaling-demo
  syncPolicy:
    automated:
      # delete if resource does not exist in desired state
      prune: false
      selfHeal: false
